pipeline:
    docker:
        image: plugins/docker
        dockerfile: Dockerfile
        repo: sirboops/mastodon
        tags: [2.6.5, latest]
        experimental: true
        squash: true
        secrets: [ docker_username, docker_password ]
