pipeline:
    docker:
        image: plugins/docker
        dockerfile: Dockerfile
        repo: sirboops/mastodon
        tags: [3.0.1-alpine, latest-alpine]
        experimental: true
        squash: true
        secrets: [ docker_username, docker_password ]
