pipeline:
    docker:
        image: plugins/docker
        dockerfile: Dockerfile
        repo: sirboops/mastodon
        tags: [2.8.2, latest]
        experimental: true
        squash: true
        secrets: [ docker_username, docker_password ]
